[package]
name = "Settlers4LinuxPatcher"
version = "1.0.0"
edition = "2021"
authors = ["R.H."]
license = "GPL-3.0"
description = "A tool to patch Settlers 4 on Linux systems."

[dependencies]
# GUI
iced = { version = "0.14", features = ["advanced", "wgpu"] }
iced_fonts = { version = "0.3", features = ["bootstrap"] }
display-info = "0.5"
rfd = "0.16"

# Hashing
sha1 = "0.10"
hex = "0.4"

# Error handling
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.13"

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1"

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
strip = true # Strip debug symbols
